'use strict';

const PASSWORD_SALT_SIZE_IN_BYTES = 12;
const ITERATION_COUNT = 10000;
const IV_SIZE_IN_BYTES = 12;
const KEY_SIZE_IN_BITS = 256;
const KEY_SIZE_IN_BYTES = KEY_SIZE_IN_BITS / 8;
const ENCRYPTION_MODE = 'aes-' + KEY_SIZE_IN_BITS + '-gcm';
const HMAC_MODE = 'sha256';
const PLAINTEXT_ENCODING = 'utf-8';
const CIPHERTEXT_ENCODING = 'base64';
const AUTH_TAG_LENGTH_IN_BYTES = 16;

module.exports = {
    PASSWORD_SALT_SIZE_IN_BYTES,
    ITERATION_COUNT,
    IV_SIZE_IN_BYTES,
    KEY_SIZE_IN_BITS,
    KEY_SIZE_IN_BYTES,
    ENCRYPTION_MODE,
    HMAC_MODE,
    PLAINTEXT_ENCODING,
    CIPHERTEXT_ENCODING,
    AUTH_TAG_LENGTH_IN_BYTES,
};
